### ISSUE TITLE
Fix CI failures

### ISSUE THREAD

**Issue by Mikolaj** [iconnect/ridley#13]
@adinapoli: I wonder, could you have a quick look at https://travis-ci.org/iconnect/ridley/builds/235528181 and venture a guess as to the cause of the few failures there, the ones in tests run via stack? I'm quite puzzled because the same tests pass on OSX and similar tests (package versions may differ) pass when run with cabal. Thank you!

**Comment by Mikolaj** [comment]
@adinapoli: ping :)

**Comment by Mikolaj** [comment]
The failing CI entries actually fixed themselves (at least in my PR, but it may be unrelated), while I've broken the other ones in my PR (wrong version of template-haskell is being installed, e.g., in https://travis-ci.org/iconnect/ridley/builds/486617001), so I'm not closing the issue.

**Comment by Mikolaj** [comment]
While we are at it, fixing all warnings would be good. In particular I introduced some by not defining (even under ifdefs) the new methods of `Katip Ridley` and `KatipContext Ridley`. Since tests pass, I think the new methods are not used in our contexts, but a more explicit error message, or a trivial implementation, would be welcome.

**Comment by adinapoli** [comment]
Fixed by https://github.com/iconnect/ridley/pull/21
