### ISSUE TITLE
Duplicate symbol '_set_ridley_ifi_data' when building on Darwin

### ISSUE THREAD

**Issue by adinapoli** [iconnect/ridley#18]
While building Hermes I've ran into a weird build failure with Ridley (that it used to work just fine in the old days). In particular, while building `master` with `cabal new-build all`, This is the result:

```
(ghc-8.6.5) ridley/ridley (master●) > cabal new-build all                                                             
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - ridley-0.3.1.3 (lib) (file src/System/Metrics/Prometheus/Ridley/Metrics/Network/Darwin.c changed)
Preprocessing library for ridley-0.3.1.3..
Building library for ridley-0.3.1.3..
duplicate symbol '_set_ridley_ifi_data' in:
    /Users/adinapoli/work/clients/IRIS/ridley/ridley/dist-newstyle/build/x86_64-osx/ghc-8.6.5/ridley-0.3.1.3/build/System/Metrics/Prometheus/Ridley/Metrics/Network/Darwin.dyn_o
    /Users/adinapoli/work/clients/IRIS/ridley/ridley/dist-newstyle/build/x86_64-osx/ghc-8.6.5/ridley-0.3.1.3/build/src/System/Metrics/Prometheus/Ridley/Metrics/Network/Darwin.dyn_o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
```

The culprit I think is to be researched in how I am (mis)using `inline-c`, I think. Probably I am either declaring things twice or somehow failing to instruct the C compiler to not redefine the function multiple times, although I must be missing something, but it has been a while since I have hacked on `ridley`.

For my current hacking session within `hermes-server` I ended up fixing the build by simply removing `src/System/Metrics/Prometheus/Ridley/Metrics/Network/Darwin.c` from the `c-sources` of the `.cabal` file (as an interim), but it would be nice to get at the bottom of this (but that's not urgent).

**Comment by etherz10** [comment]
Hey! Good to see you around again. @adinapoli 

I've run into that a few times when trying to build Atlas/Hermes on OSX and had to resort to my CentOS VM.

**Comment by etherz10** [comment]
@adinapoli How much work would it be to fix this? As I keep running into this when hacking on my mac and having to jump between machines is getting annoying.

Alternatively, when you're next around can you show me the workaround?

**Comment by adinapoli** [comment]
This issue has been hindering me as well, and I think that is pesky enough to deserve a proper fix. I will have to recall how `inline-c` exactly works, but it shouldn't be too hard to fix.
