### ISSUE TITLE
Choose a more appropriate name?

### ISSUE THREAD

**Issue by adinapoli** [iconnect/ridley#2]
cc-ing @cdornan @filib @t-c-k  @adamgundry for brainstorming.

🚲  **Bikeshedding warning! Run, you fools!** 🚲 

When I created this package I gave the name Scott mostly as a twofold pun:

* Ridley Scott is actually the main director of [Prometheus](https://en.wikipedia.org/wiki/Prometheus_(2012_film))
* It was a tribute to Scott-ish oatmeal (I think it escalated a bit from cereal, porridge, oatmeal and finally Scott, but cannot remember exactly the details).

I think the name was a witty one as long as this was an internal package, but if we want to release this into the wild and hope for it to be useful outside of our company, I see two problems with the current name:

* It almost clashes with [Scotty](http://hackage.haskell.org/package/scotty), the popular web framework. If we upload this package on Hackage we'll generate only confusion with people thinking the two projects are somehow related. It could also (potentially?) screw the Hackage search algorithm if that's based of the Levenshtein distance, with is only 1 between Scotty and Scott.

* It doesn't help with discoverability. If I'm searching for a Prometheus library for Haskell and I use google chances are I might hit the GH repo, but if I search only via Hackage the package won't show up (unless we put the word "Prometheus" into the description so that Hackage can index it). But even if this is only a false concern I still find the name misleading.

Therefore, I'm asking you guys:

1. Do you think we should change the name before going public and upload this on Hackage?
2. Which name should we use? (Ah, one of the 3 most difficult things in CS 😛 ). Ideally the idea I would like to convey is essentially this is an opinionated library which exposes a bunch of system & GHC stats, for lazy devops, basically. Currently the list of exposed metrics cannot even be customised (but should be possible with future releases of the lib). As this is more a "end-consumer" library rather than a "library-authors" one, seems like the convention is to go with a proper name (e.g. "EKG").

Ultimately I like the name "Scott", I'm just genuinely concerned about the Scott/Scotty confusion.

**Comment by philipcunningham** [comment]
I think a more descriptive name that encompasses `wai`, `ekg` and `prometheus` would be more discoverable but I don't have any suggestions.

**Comment by adamgundry** [comment]
I think that confusion with Scotty is a valid concern. I'd be slightly less concerned about discoverability (the package summary and description can mention all the relevant keywords, so Google/Hackage will match them). Names are hard!

By the way, how does (insert package name here) compare to `prometheus-client`/`prometheus-metrics-ghc`/`wai-middleware-prometheus`, which I've just come across?

**Comment by cdornan** [comment]
I also think the potential for confusion with Scotty is a concern, but, In the absence of any more sensible suggestion, I would definitely go for ripley! That she isn't in the film just makes it even better.

A boring name would probably be safer though.

**Comment by adinapoli** [comment]
> By the way, how does (insert package name here) compare to...

Let's start 😛 

> prometheus-client

<Package> is not a client library (I had the very same private convo with Ollie Charles about this). A client library is something which plugs directly into your library as a middleware and acts as a bridge between you and prometheus, exposing the stats (counters, gauges, etc) in a format Prometheus can scrape. Incidentally, Ollie is working on another client [that you can find here](https://github.com/ocharles/prometheus-effect). <Package> instead piggybacks on `prometheus` (another, ihmo better designed client library) to expose useful stats.

> prometheus-metrics-ghc

This guy exposes only one thing, which are GHC RTS metrics, whereas <Package> does more, in a sense. Furthermore it has a dep from `prometheus-client`, which is a no-go for us as it would cause us to have 2 client libs in the same project. Not surprisingly they are from the same author 😉 

> wai-middleware-prometheus

Same story but with `wai` middleware stats.

All in all it seems that those 3 lib (all gathered into an umbrella GH repo) are fulfilling a similar goal than I was but I choose a monolithic library, EKG-style, to be a one-stop shop for "lazy devops", essentially, instead a set of micro-reusable libraries. The reusability here is simply a bogus claim as it locks you down to use a single prometheus client, so why bother in the first place? 😜 
But in all seriousness, what that lacks are the system metrics; they are using RTS stats whereas <Package> hooks directly into EKG's `Store`, so you get way more out of that. On top of that you also get for free:

* CPU stats
* Disk Usage
* Network Stats

Now, one of the main critique Ollie moved was that this is reinventing the wheel as there is already an official [node-exporter](https://github.com/prometheus/node_exporter) which offers that *and more*, but the catch is that you have to enable it on the monitored machine. What I wanted instead was a dep-free package you could tell people "look, install this and get some use out of it".

Ops, I wrote a poem again..

> I would definitely go for ripley

That's not a bad name! I like the fact it's a proper noun and it doesn't clash on any package on Hackage. The only caveat is that is suggest that you can "replay" events or some kind of Tardis monad 😬  Maybe playing a bit with that, another option would go with **Ridley**, basically Scott's first name (Scott aka the main director), although the name doesn't convey absolutely nothing, apart the very crafty association Prometheus Film -> Director -> Scott -> Ridley 😀

**Comment by cdornan** [comment]
@adinapoli yes Ridley would be a great move (and there is of course an excellent precedent with the first name being chosen because it works better).

**Comment by adinapoli** [comment]
I eventually settled on "Ridley", just for the sake of pushing this forward 😉
