### ISSUE TITLE
CPU load not being calculated correctly

### ISSUE THREAD

**Issue by adamgundry** [iconnect/ridley#8]
I just noticed that `getLoadAvg` is always returning -1 three times, because (at least on some systems) `/proc/loadavg` returns something like `3.42 5.85 4.68 5/686 20011` in a single line, which isn't parsed correctly by the current code.

**Comment by adinapoli** [comment]
Hey Adam, thanks for this bug report. I was indeed wondering why that was the case. Will swiftly get this sorted out as I'm working on Ridley this minute anyway.
